"""create opportunities and applications tables

Revision ID: 1920ddd1a542
Revises: e6786b7b5b61
Create Date: 2026-07-12 11:04:57.629123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1920ddd1a542'
down_revision: Union[str, None] = 'e6786b7b5b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
