"""add unique constraint on opportunities source_id

Revision ID: 20fe70ccfc56
Revises: 1920ddd1a542
Create Date: 2026-07-14 12:04:05.314187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fe70ccfc56'
down_revision: Union[str, None] = '1920ddd1a542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
