"""add profile fields to users

Revision ID: 41e5b4937ddb
Revises: 20fe70ccfc56
Create Date: 2026-07-20 16:26:10.612783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e5b4937ddb'
down_revision: Union[str, None] = '20fe70ccfc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
